version: '3'
services:
  web:
    build: .
    depends_on:
    - db
    ports:
    - "8080:8080"
    volumes:
    - .:/opt/app
    - /opt/app/node_modules
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bob
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=bob
    ports:
      - "27017:27017"
volumes:
  mongodata: